"""Subclass of UI, which is generated by wxFormBuilder."""

import wx
import frame

# Implementing UI
class frameUI( frame.UI ):
	def __init__( self, parent ):
		frame.UI.__init__( self, parent )
	
	# Handlers for UI events.
	def buttonStartOnClick( self, event ):
		# TODO: Implement buttonStartOnClick
		pass
	
	def buttonSaveOnClick( self, event ):
		# TODO: Implement buttonSaveOnClick
		pass
	
	def buttonCloseOnClick( self, event ):
		# TODO: Implement buttonCloseOnClick
		pass
	
	
